### ISSUE TITLE
May Meetup - Trevor Pierce

### ISSUE THREAD

**Issue by blainekasten** [NebraskaJS/LNK#10]
@1Copenut, please drop talk details here.
##### TODOs
- [ ] Solidify Location/Food
- [ ] Post Meetup
- [ ] Record Video
- [ ] Post Video on nebraskajs.com

**Comment by 1Copenut** [comment]
**TALK:**
The Strange DOM: Or How I Learned to Stop Worrying and Test for Accessibility

**DESCRIPTION:**
Accessibility is an often overlooked part of front-end development. It's usually relegated to a box that gets checked off just before--or after--a site goes into production. The United States lags behind the rest of the industrialized world in firm guidance, so we as web developers can help lead the way.

I will be speaking to why accessibility looks easy, but ends up being difficult, and demonstrating the test chain I've created to find and fix #a11y errors.

[C3 Toolchain Accessibility Testing](https://github.com/1Copenut/C3/tree/develop)

Please check out the develop branch, master is way behind and due for a 2.0 tagged release.

**Comment by blainekasten** [comment]
Sorry to everyone who has been waiting  for the next meetup. March was cancelled due to lack of parking in the haymarket. April was never scheduled due to conflicting schedules. The next meetup in May will be the continuation of what was supposed to be. @1Copenut will be giving his talk
