### ISSUE TITLE
February Meetup - Steve Chikwaya

### ISSUE THREAD

**Issue by blainekasten** [NebraskaJS/LNK#11]
Still looking for a speaker. If interested, drop a line. If not sure what to talk about, see #4 

TODOS
- [x] Find speaker
- [ ] Solidify Venue
- [ ] Solidify Food
- [ ] Tape Meetup
- [ ] Post Meetup on nebraskajs.com

**Comment by blainekasten** [comment]
@stavarotti has proposed talking about npm hacks and tricks

**Comment by stavarotti** [comment]
**Title:**
Knowing your tools - npm

**Description:**
In this talk, we will shine light on npm and look at some of its unknown and misunderstood features.

**Comment by blainekasten** [comment]
http://www.meetup.com/nebraskajs/events/227607994/
