### ISSUE TITLE
December Meetup - Webpack All The Things

### ISSUE THREAD

**Issue by blainekasten** [NebraskaJS/LNK#5]
#### NEW LOCATION!

Recently, we've had a lot of conflicts with downtown parking because of events at PBA. For this reason, we are going to play around with the idea of leaving downtown. Justin Baker and Zillow have been kind of enough to host Decembers meetup! So let's meet down in the south east and nerd out!
#### Announcement!

With the goal to create a good community of friends, colleagues and encouragers; We'll be announcing a github repo we want to use to facilitate discussion around the meetup. Sneak Peak [here](github.com/NebraskaJS/LNK).
#### Sean Larkin - Webpack All The Things

Sean will be diving deep into the world of Webpack and why you should be using it to bundle all the things. React projects, Angular projects, and even NPM modules.
#### Beer.js

There are a couple bars around the area we will go to grab a drink afterwards. Location TBA.

**Comment by nmschulte** [comment]
@blainekasten, I don't suppose your slides/content will be available beforehand, will it?  Thanks for starting this, it'll be interesting to see how it fares.

**Comment by blainekasten** [comment]
@TheLarkInn, is that something you could do?

Thanks @nmschulte! I'm hoping this helps everyone stay connected as a group.

**Comment by TheLarkInn** [comment]
I can try to for sure :)

**Comment by TheLarkInn** [comment]
### Links
- [Presentation Slides](http://slides.com/seanlarkin/webpack-all-the-things-2015/)
- [Angular ES6 Starter Repo](https://github.com/TheLarkInn/angular-starter-es6-webpack)
- [Webpack Cookbook](https://github.com/christianalfoni/react-webpack-cookbook)
