### ISSUE TITLE
January Meetup - Cole Voss

### ISSUE THREAD

**Issue by blainekasten** [NebraskaJS/LNK#6]
@colevoss has been accepted to give a lightning talk at [reactconf](http://conf.reactjs.com/)! 
He will be giving a preview presentation to help him practice for the conference. Details to come
##### TODOs
- [x] Solidify location/food
- [x] Post Meetup details

**Comment by TheLarkInn** [comment]
Way to go @colevoss. How many of us get free tickets? :+1:

**Comment by blainekasten** [comment]
There will be no recording of this meetup since it is his trial run for the conference. The conference will be recording the talk.

**Comment by ezbakejustin** [comment]
As of right now food will be catered by Greta's: a few kinds of chicken wings and salad.

**Comment by blainekasten** [comment]
:trophy:

**Comment by blainekasten** [comment]
https://docs.google.com/presentation/d/1IqRvyiCiDjOTB7f69Xu4LL0HX9Lst_LK12Rwa2SHzzg/edit#slide=id.p
